_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 128
  BASE_LR: 0.08
  STEPS: (69600, 92800)
  MAX_ITER: 116000
  WARMUP_ITERS: 3625
TEST:
  EVAL_PERIOD: 29000
VIS_PERIOD: 2320
DATASETS:
  TRAIN: ('SUNRGBD_train', 'SUNRGBD_val', 'Hypersim_train', 'Hypersim_val', 'ARKitScenes_train', 'ARKitScenes_val')
  TEST: ('SUNRGBD_test', 'Hypersim_test', 'ARKitScenes_test') 
  CATEGORY_NAMES: ('stationery', 'sink', 'table', 'floor mat', 'bottle', 'bookcase', 'bin', 'blinds', 'pillow', 'bicycle', 'refrigerator', 'night stand', 'chair', 'sofa', 'books', 'oven', 'towel', 'cabinet', 'window', 'curtain', 'bathtub', 'laptop', 'desk', 'television', 'clothes', 'stove', 'cup', 'shelves', 'box', 'shoes', 'mirror', 'door', 'picture', 'lamp', 'machine', 'counter', 'bed', 'toilet')
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 38